const PAGE_SIZE = 4096;

// master header
const MH_IDENTIFICATOR_POSITION = 0;
const MH_VERSION_POSITION = 4;
const MH_PAGE_SIZE_POSITION = 5;
const MH_NEXT_FREE_PAGE_ID_POSITION = 7;

// base page headers
const NEXT_PAGE_ID_POSITION = 0;
const NEXT_SLOT_OFFSET_POSITION = 4;
const RECORD_COUNT_POSITION = 6;
const PAGE_TYPE_POSITION = 15;

// catalog slot sizes
const TABLE_SLOT_SIZE = 64;
const COLUMN_SLOT_SIZE = 48;

const PAGE_TYPES = {
    MASTER_NULL_MAP: 1,
    CATALOG_TABLE: 2,
    CATALOG_COLUMN: 3,
    DATA_SLOTTED: 4,
    DATA_FIXED: 5,
    DATA_BITMAP: 6,
} as const;

const DATA_TYPES = {
    BOOLEAN: 1,
    INTEGER: 2,
    STRING: 3,
    FOREIGN_KEY: 4,
};

export type PageType = (typeof PAGE_TYPES)[keyof typeof PAGE_TYPES];

export {
    MH_IDENTIFICATOR_POSITION,
    MH_NEXT_FREE_PAGE_ID_POSITION,
    MH_PAGE_SIZE_POSITION,
    MH_VERSION_POSITION,
    PAGE_SIZE,
    NEXT_PAGE_ID_POSITION,
    NEXT_SLOT_OFFSET_POSITION,
    RECORD_COUNT_POSITION,
    PAGE_TYPE_POSITION,
    PAGE_TYPES,
    DATA_TYPES,
    TABLE_SLOT_SIZE,
    COLUMN_SLOT_SIZE,
};
